departments = {"1":'Human Resources (HR)',
"2":'Finance',
"3":'Marketing',
"4":'Sales',
"5":'Customer Service',
"5":'Information Technology (IT)',
"5":'Research and Development (R&D)',
"5":'Operations',
"5":'Legal',
"5":'Product Development',
"5":'Supply Chain Management',
"5":'Public Relations (PR)',
"5":'Corporate Communications',
"5":'Business Development',
"5":'Creative Services',
"5":'Design',
"5":'Quality Assurance (QA)',
"5":'Training and Development',
"5":'Facilities Management',
"5":'Security',
"5":'Compliance',
"5":'Accounting',
"5":'Strategy and Planning',
"5":'Administration',
"5":'Procurement',
"5":'Health and Safety',
"5":'Project Management',
"5":'Client Relations',
"5":'Event Planning',
"5":'Data Analytics'}